from api.errors.codes import ErrorCode
from api.errors.exceptions import (
    AccessTokenExpiredError,
    AccountDisabledError,
    AccountLockedError,
    AccountPendingError,
    AppError,
    ConflictError,
    EmailAlreadyExistsError,
    InvalidCredentialsError,
    InvalidRefreshTokenError,
    InvalidRequestBodyError,
    InvalidStatusTransitionError,
    LastAdminProtectedError,
    NotFoundError,
    OldPasswordMismatchError,
    PasswordTooWeakError,
    PermissionDeniedError,
    RateLimitedError,
    RefreshTokenExpiredError,
    RegistrationDisabledError,
    SelfDowngradeForbiddenError,
    UnauthenticatedError,
    UserNotFoundError,
    ValidationError,
    VersionConflictError,
)
from api.errors.middleware import register_exception_handlers

__all__ = [
    "AccessTokenExpiredError",
    "AccountDisabledError",
    "AccountLockedError",
    "AccountPendingError",
    "AppError",
    "ConflictError",
    "EmailAlreadyExistsError",
    "ErrorCode",
    "InvalidCredentialsError",
    "InvalidRefreshTokenError",
    "InvalidRequestBodyError",
    "InvalidStatusTransitionError",
    "LastAdminProtectedError",
    "NotFoundError",
    "OldPasswordMismatchError",
    "PasswordTooWeakError",
    "PermissionDeniedError",
    "RateLimitedError",
    "RefreshTokenExpiredError",
    "RegistrationDisabledError",
    "SelfDowngradeForbiddenError",
    "UnauthenticatedError",
    "UserNotFoundError",
    "ValidationError",
    "VersionConflictError",
    "register_exception_handlers",
]
