export const settingsStrings = {
  myProjects: "我的项目",
  projectName: "AI云平台竞品分析",
  settings: "设置",
  basicInfo: "基本信息",
  memberManagement: "成员管理",
  aiConfig: "AI配置",
  inviteMember: "邀请成员",
  avatar: "头像",
  username: "用户名",
  email: "邮箱",
  role: "角色",
  action: "操作",
  admin: "管理员",
  editor: "编辑者",
  viewer: "查看者",
  editRole: "修改角色",
  remove: "移除",
  aiProvider: "AI Provider",
  localMode: "本地模式",
  saveConfig: "保存配置",
  userName: "陈琦",
  userInitials: "陈",
};

export const settingsMembers = [
  {
    name: "陈琦",
    initials: "陈",
    email: "cy@example.com",
    role: "管理员",
    roleVariant: "default" as const,
    canEdit: false,
  },
  {
    name: "Mentor",
    initials: "M",
    email: "mentor@example.com",
    role: "编辑者",
    roleVariant: "green" as const,
    canEdit: true,
  },
  {
    name: "同事X",
    initials: "X",
    email: "colleague@example.com",
    role: "查看者",
    roleVariant: "secondary" as const,
    canEdit: true,
  },
];
